version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: death-note-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - deathnote-network

  death-note-app:
    build: .
    container_name: death-note-java-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    volumes:
      - ./my-uploads:/app/uploads
    networks:
      - deathnote-network

networks:
  deathnote-network:
    driver: bridge

volumes:
  mongo_data: